### ISSUE TITLE
Unable to online-migrate, create, start or delete VM's due to malformed JSON String

### ISSUE THREAD

**Issue by UnwantedWarrior** [LINBIT/linstor-proxmox#19] opened 2019-05-27 14:47 UTC
Hi anyone,

so we just upgraded our linstor and proxmox setup.
Version information right here:

> root@node1:~# cat /proc/drbd 
> version: 9.0.17-1 (api:2/proto:86-114)
> GIT-hash: b9abab2dd27313922797d026542b399870bfd13e build by root@node1, 2019-05-23 06:54:11
> Transports (api:16): tcp (9.0.17-1)

> root@node1:~# dpkg -l | grep linstor
> ii  linstor-client                       0.9.4-1                        all          Linstor client command line tool
> ii  linstor-common                       0.9.9-1                        all          DRBD distributed resource management utility
> ii  linstor-proxmox                      3.0.3-1                        all          DRBD distributed resource management utility
> ii  linstor-satellite                    0.9.9-1                        all          DRBD distributed resource management utility
> ii  python-linstor                       0.9.4-1                        all          Linstor python api library

> root@linstor-controller:~# dpkg -l | grep linstor
> ii  linstor-client                  0.9.4-1                        all          Linstor client command line tool
> ii  linstor-common                  0.9.9-1                        all          DRBD distributed resource management utility
> ii  linstor-controller              0.9.9-1                        all          DRBD distributed resource management utility
> ii  python-linstor                  0.9.4-1                        all          Linstor python api library

Our issue now is, that we're unable to online-migrate, start. create or delete an VM.
Most likely this is a bug.

Error message from proxmox is the following:

> 
> Traceback (most recent call last):
>   File "/usr/bin/linstor", line 24, in <module>
>     linstor_client_main.main()
>   File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 627, in main
>     LinStorCLI().run()
>   File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 592, in run
>     rc = self.parse_and_execute(sys.argv[1:])
>   File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 307, in parse_and_execute
>     rc = args.func(args)
>   File "/usr/lib/python2.7/dist-packages/linstor_client/commands/rsc_cmds.py", line 485, in list
>     lstmsg = self._linstor.resource_list(filter_by_nodes=args.nodes, filter_by_resources=args.resources)
>   File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 1264, in resource_list
>     return self.volume_list(filter_by_nodes=filter_by_nodes, filter_by_resources=filter_by_resources)
>   File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 1291, in volume_list
>     path
>   File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 198, in _rest_request
>     error_data = json.loads(error_data_raw)
>   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
> TASK ERROR: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 126, <$pipe> chunk 1.

I already saw the commit 13 days ago which seems very corresponding to our issue.

Starting the VM manually with the output of `qm showcmd <vmid>` works absolutely fine.

Can i provide some information for you to get this fixed ?

Kind Regards,
UnwantedWarrior

**Comment by rck** [comment] 2019-05-27 14:59
Duplicate of #17 

Please upgrade

**Closed by rck** 2019-05-27 14:59 UTC
